import Head from "next/head";
import styles from "../styles/Home.module.css";
import Link from "next/link";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h2>
        <Link href="/csr/user">CSR</Link>
      </h2>
      <h2>
        <Link href="/ssr/user">SSR</Link>
      </h2>
      <h2>
        <Link href="/ssg/user">SSG</Link>
      </h2>
    </div>
  );
}
